#+title: Health Care Credentialing
- tags: [[file:20201211192342-xdemic.org][xdemic]]

bibliographystyle:aunsrt
bibliography:xdemic.bib

* Quick facts about credentialing
- The inefficient credentialing process is costly to providers and payers. [[https://www.caqh.org/sites/default/files/solutions/events/2011/q4/IssueBrief.pdf][The Council for Affordable Quality Healthcare]] estimates that payers spend more than $2 billion a year maintaining provider databases.

- Each physician in a practice submits an average of 18 applications for credentialing each year. That requires 80 minutes—including 69 minutes of staff time and 11 of physician time—per physician. Payers then spend time and money verifying these claims.

- [[http://www.namss.org/Portals/0/Policies_And_Bylaws/Official%20NAMSS%202017%20Roundtable%20Report.pdf][The National Association of Medical Staff Services (NAMSS)]] estimates that most physician credentialing takes more than 120 days, while health plan enrollment takes 60 to 180 days.

- Credentialing and directory updates to list locations where a physician sees patients and whether a physician is enrolled with a certain insurer or is taking new patients. NAMSS estimates that 12 to 18 percent of provider directories are out of date or incorrectly list a provider as participating in a plan.

- A recent CMS [[https://www.cms.gov/Medicare/Health-Plans/ManagedCareMarketing/Downloads/Provider_Directory_Review_Industry_Report_Round_2_Updated_1-31-18.pdf][audit]] of Medicare Advantage online provider directories found that 52.2 percent contained inaccuracies. According to CMS’ 2019 call letter, it will begin taking enforcement actions against some Medicare Advantage organizations that don’t correct serious provider directory deficiencies.
* Executive Summary
Hospitals and other health care organizations have traditionally viewed credentialing as a regulatory burden.(add reference) More continuous monitoring is neglected because of the time and cost involved with manually validating employee records against various primary sources--potentially affecting the quality of patient care.(add reference) Intiva Health conducted a survey that involved medical staff in a variety of health care facilities. Participants detailed the various hurdles involved with credentialing providers.
* Introduction
Over the past 20 years, the credential management process within the health care sector in the United States has become complex and onerous primarily due to the expansion of the provider scope of practice, accrediting bodies, and requirements of third-party payers like Medicare, Medicaid, and private insurers cite:patel2018credentialing. It can take anywhere from a few weeks to six months to get credentialed. (add reference)

In addition it takes approximately 20 hours per credentialing application form. If any elements are missing from the application, or if a school, employer, or reference doesn’t swiftly respond to verification requests, it can add weeks or even months to the process. All of this time spent waiting on credentials is time that could be utilized focusing on patient care, and ultimately represents a loss of revenue for the health care facility. (add reference)
The credential management process must be re-done every two years in addition to fulfilling
continuing medical education (CME) requirements.

In combination with other non-clinical paperwork, this administrative burden takes up nearly nine
hours a week for the average doctor, according to a study published in the International Journal of Health Services cite:himmelstein2014comparison.

* Current Method of Professional Credentialing
Healthcare institutions are responsible for keeping patients safe while delivering high standards of care. To accomplish this, facilities must confirm the competency of their staff. Credentialing is a process that ensures healthcare providers have the proper qualifications, training, licensure, and ability to provide direct patient care cite:patel2018credentialing. Documentation verification may include state license, drug enforcement agency (DEA) license, board certification, education, on-going training, hospital affiliation, and malpractice insurance. This process entails contacting a multitude of organizations to authenticate the information. All healthcare professionals regulated by a licensing body to provide care, without supervision or direction within the scope of the individual’s license, must be credentialed cite:patel2018credentialing. Many practitioners work in dozens of healthcare settings and are required to maintain credentials with each one resulting in great redundancy.

Through their [[https://www.ncqa.org/programs/health-plans/credentials-verification-organization-cvo/][Credentials Verification Organization (CVO)]] the National Committee for Quality Assurance (NCQA) will verify credentials such as diplomas and degrees with the primary source. The National Practitioner Data Bank (NPDB), a program of the U.S. Department of Health & Human Services, is a web-based warehouse of reports containing information on medical malpractice payments and adverse actions related to health care practitioners, providers, and suppliers. The American Board of Medical Specialties (ABMS) certifies 150 medical specialties while the American Association of Nurse Practitioners (AANP) and the American Nurses Credentialing Center (ANCC) will verify nurse board certification.

